name: RandomAdditions
version: '${project.version}'
main: eu.pommeray.random_additions.RandomAdditions
api-version: '1.20'
commands:
  calculator:
    description: Allows calculations of simple expressions
    usage: /calculator <firstNumber> <operation> <secondNumber>
    permission: random_additions.calculator